export const localizedStrings = {
  en: {
    "widget.slider.voteButton.label": "submit",
    "chat.messageDeleted": "This message was deleted",
    "chat.mutedMessage": "Unable to send message",
    "chat.quoteMessage.deleted": "Message has been deleted by <nickname>",
    "chat.scrollDownButton.label": "",
    "chat.confirmation.deleteMessage.title": "Delete Message?",
    "chat.confirmation.deleteMessage.description":
      "This message will be removed for everyone",
    "chat.confirmation.deleteMessage.accept": "Yes, continue",
    "chat.confirmation.deleteMessage.reject": "Cancel",
    "chat.blockConfirmation.message": "This user has been blocked",
    "chat.reportConfirmation.message": "Message has been reported",
    "chat.messageMenu.quote": "Reply to message",
  },
  pl: {
    "widget.slider.voteButton.label": "Wyślij",
    "chat.messageDeleted": "Wiadomość została usunięta",
    "chat.mutedMessage": "Nie możesz wysłać wiadomości",
    "chat.quoteMessage.deleted": "Wiadomość została usunięta przez",
    "chat.scrollDownButton.label": "",
    "chat.confirmation.deleteMessage.title": "Czy usunąć wiadomość?",
    "chat.confirmation.deleteMessage.description":
    "Ta wiadomość zostanie usunięta wszędzie",
    "chat.confirmation.deleteMessage.accept": "Tak, usuń",
    "chat.confirmation.deleteMessage.reject": "Anuluj",
    "chat.messageMenu.quote": "Odpowiedz na wiadomość",
    "chat.messageMenu.reportMessage": "Zgłoś wiadomość",
    "chat.messageMenu.blockUser": "Zablokuj użytkownika",
    "chat.messageMenu.deleteMessage": "Usuń Wiadomość",
    "chat.blockConfirmation.message": "Ten użytkownik został zablokowany",
    "chat.reportConfirmation.message": "Wiadomość została zgłoszona",
    "widget.button.submit": "Głosuj",
    "widget.button.submitted": "Zapisane",
    "widget.quiz.correct.answer": "Dobra Odpowiedź!",
    "widget.quiz.wrong.answer": "Zła odpowiedź!",
    "livechat.quoteMessageItem.replyTo.label": "Odpowiedz na",
    "livechat.userSetting.chatSetting.label": "Ustawienia użytkownika",
    "livechat.userSetting.username.label": "Nazwa",
    "livechat.userSetting.colorPicker.title": "Kolor",
    "livechat.userSetting.colorPicker.description": "Zmiana może zająć kilka minut.",
    'chat.inputPlaceholder': 'Napisz coś',
    'chat.confirmation.deleteMessage.loadinglabel': 'Usuwanie',
    'chat.previousMessage.load': 'Załaduj poprzednie wiadomości',
    'chat.previousMessage.loading': 'Ładowanie poprzednich wiadomości',
    'chat.messageSenderBlocked': "Nadawca wiadomości zablokowany",
    'widget.timeline.loadMore': 'Załaduj Więcej'
  }
};
